version: "3.8"

services:
  app:
    build: ./app
    image: devops-lab:v1
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
